spring:
  application:
    name: pick-N-pack-Man

  datasource:
    url: jdbc:postgresql://localhost:6432/pick_n_pack_man
    username: ${DB_USERNAME:pnp}
    password: ${DB_PASSWORD:pnp1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
